language: csharp
solution: ArrangeWF.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ArrangeWF.sln
after_script:
  - xbuild ArrangeWF.sln
  - nunit-console UnitTest/bin/Debug/UnitTest.dll