language: csharp
solution: ArrangeWF.sln

install:
  - nuget restore ArrangeWF.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - xvfb-run make test
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTest/bin/Release/UnitTest.dll